### PR TITLE
Abstract database from handlers

### PR DESCRIPTION
**Pull request by lsmoura**

### CODE REVIEW

**Comment by ddworken** [comment]
Thanks for this! The failing Go Tests are due to my recent test reliability work which accidentally required access to an API key that isn't available when you run them. cc10689 fixes this, so if you merge in master you should be able to run the Go Tests on github actions.

**Comment by lsmoura** [comment]
Apparently some constants weren't available on 3.18. I'll fix those.

**Comment by lsmoura** [comment]
@ddworken tests are finally passing!

**Comment by ddworken** [comment]
This is awesome, thank you!

**Pull request merged**
